- name: "Create Backend App Directory"
  file:
    path: /home/ubuntu/udapeople-backend-app
    state: directory

- name: "Extract Backend Artifact"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/udapeople-backend-app

- name: "Install Dependencies"
  shell: |
    cd /home/ubuntu/udapeople-backend-app
    npm install

- name: "Start Backend Service"
  become: true
  shell: |
    cd /home/ubuntu/udapeople-backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: backend_server

- name: "Log Messages"
  debug:
    msg: "{{ backend_server.stdout_lines }}"
